# converts CSV generated by JavaScript into PHP 
import os
import csv

directory = "controllers-output/"

with open('controllers.csv', 'r') as csvfile:
  csvread = csv.reader(csvfile, delimiter='|')
  for row in csvread:
      #print type(row)
    with open( directory + row[0]+".php", "w+") as phpfile:
      phpfile.write(row[1])

